### PR TITLE
Fix mirrors new OnServerError method

### PR DESCRIPTION
**Pull request by axvemi**
It will fix the error caused on import.

### CODE REVIEW

**Comment by makinori** [comment]
Thanks for the pr. I hope it gets merged soon!

**Review by copperdevs — APPROVED** [review]

**Review by nonperforming — APPROVED** [review]

**Comment by docimin** [comment]
Why did you close this @axvemi ?

**Comment by axvemi** [comment]
@docimin It seems that when I removed the repo from my repositories it automatically closed it. Didn't know that. Sorry

**Comment by nonperforming** [comment]
@axvemi Thinking of forking the project?

**Comment by axvemi** [comment]
@nonperforming Yeah, I forked it with the fix at least until this one gets updated. See https://github.com/axvemi/FizzyFacepunch

**Comment by axvemi** [comment]
Closed in favour of the pull request from the fork. https://github.com/Chykary/FizzyFacepunch/pull/36

**Pull request closed without merging**
